import React, { useState, useEffect } from "react"; import { useTranslation } from "react-i18next"; import { ArrowRight, MapPin, Users, TrendingUp, Star, CheckCircle, Factory, Heart } from "lucide-react";
const workerStories = [ { id: 1, name: "Rajesh Kumar", location: "Gaya, Bihar", before: "Daily wage laborer, ?3,000/month", after: "Quality Control Supervisor, ?18,000/month", impact: "Family moved from mud house to concrete home, children in better schools" }, { id: 2, name: "Priya Devi", location: "Ranchi, Jharkhand", before: "Housewife, no income, dependent on husband", after: "Senior Stitcher, ?15,000/month", impact: "First woman from her village in garment industry, inspires other women" }, { id: 3, name: "Amit Singh", location: "Lucknow, Uttar Pradesh", before: "Farmer, seasonal income, ?4,000/month average", after: "Factory Supervisor, ?20,000/month", impact: "From farming to factory leadership in 6 months, supports extended family" } ];
const impactMetrics = [ { number: "50,000+", label: "Lives Transformed", description: "Real people with real stories of change", color: "text-green-600", bgColor: "bg-green-50", icon: Users }, { number: "500+", label: "Partner Factories", description: "Leading companies trust our workforce", color: "text-purple-600", bgColor: "bg-purple-50", icon: Factory }, { number: "95%", label: "Placement Rate", description: "Exceptional success in job placement", color: "text-orange-600", bgColor: "bg-orange-50", icon: TrendingUp }, { number: "?15,000", label: "Average Salary", description: "Competitive wages for our graduates", color: "text-gray-600", bgColor: "bg-gray-50", icon: Star } ];
const programs = [ { title: "AMAS - Assisted Migration for Apparel Sector", description: "Our flagship program currently active in 4 states", locations: ["Bihar", "Jharkhand", "Uttar Pradesh", "Madhya Pradesh"], features: [ "3-month intensive training + 1-month practical", "Industrial sewing machines and modern equipment", "Quality control and safety training", "6-month post-placement support" ], outcomes: "95% placement rate with leading textile companies", color: "from-green-500 to-green-600" } ];
const partners = [ "Leading Textile Manufacturers in Delhi NCR", "Apparel Companies in Mumbai and Bangalore", "Home Textiles Industry in Chennai", "Technical Textiles in Gujarat" ];
export default function NewLandingPage() { const { t } = useTranslation(); return ( <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-green-50">
      {/* Hero Section - The Real Story */}      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">        {/* Background Elements */}        <div className="absolute inset-0">          <div className="absolute top-0 left-1/4 w-72 h-72 bg-orange-200 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-float"></div>          <div className="absolute top-0 right-1/4 w-72 h-72 bg-green-200 rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-float" style={{ animationDelay: "2s" }}></div>        </div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">          {/* Main Headline */}          <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-gray-900 mb-8 leading-tight">            From <span className="text-orange-600">Bihar's Villages</span> to <span className="text-green-600">India's Garment Factories</span>          </h1>
          {/* Story Subheadline */}          <p className="text-xl md:text-2xl text-gray-700 mb-12 max-w-4xl mx-auto leading-relaxed">            Meet <span className="font-semibold text-purple-600">Rajesh from Gaya</span> who went from earning ?3,000/month in farming to ?18,000/month as a skilled garment worker.             His story is one of <span className="font-semibold text-green-600">50,000+ lives transformed</span> through GreyBeez.          </p>
          {/* Call to Action */}          <div className="flex flex-col sm:flex-row gap-6 justify-center items-center">            <button className="bg-gradient-to-r from-green-600 to-green-700 text-white px-8 py-4 rounded-xl font-semibold text-lg hover:from-green-700 hover:to-green-800 transform hover:scale-105 transition-all duration-300 shadow-lg flex items-center">              See Rajesh's Story              <ArrowRight className="w-5 h-5 ml-2" />            </button>            <button className="border-2 border-orange-600 text-orange-600 px-8 py-4 rounded-xl font-semibold text-lg hover:bg-orange-600 hover:text-white transform hover:scale-105 transition-all duration-300">              Join the Transformation            </button>          </div>        </div>      </section>
      {/* Impact Section - Real Stories, Real Numbers */}      <section className="py-20 bg-white">        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">          {/* Section Header */}          <div className="text-center mb-16">            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">              Real Stories, <span className="text-green-600">Real Transformation</span>            </h2>            <p className="text-xl text-gray-600 max-w-3xl mx-auto">              Every number has a story, every statistic has a face. Here are the real people behind our impact.            </p>          </div>
        </div>      </section>    </div>  ); }
